// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAuth } from "firebase/auth";
import { update } from "firebase/database";
import {
  getFirestore, collection, getDocs,
  addDoc,
  doc,
  updateDoc
} from "firebase/firestore"
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
const firebaseConfig = {
  apiKey: "AIzaSyBWui1W0CBRAzvrMqHCOBUc3hMkmo3KkXw",
  authDomain: "tdt4140-prosjekt.firebaseapp.com",
  databaseURL: "https://tdt4140-prosjekt-default-rtdb.europe-west1.firebasedatabase.app",
  projectId: "tdt4140-prosjekt",
  storageBucket: "tdt4140-prosjekt.appspot.com",
  messagingSenderId: "807771308285",
  appId: "1:807771308285:web:43ebb655b020317c987e94"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
export const auth = getAuth(app)

/* class firebaseControl {
  static getAuth(): import("@firebase/auth").Auth {
    //throw new Error('Method not implemented.');
    return auth;
  } */

  class firebaseControl {
    static getAuth() {
      return auth;
    }

  async getDestinastions(){
    const destinationsCol = collection(db, "destinations");
    const destinationsSnapshot = await getDocs(destinationsCol);
    const destinationsList = destinationsSnapshot.docs.map(doc => doc.data());
    return destinationsList;
  }

  async addDestination(addCity: string, addCountry: string, addImgURL?: string, addCategory?: string[], addDescription?: string) {
    const collectionRef = collection(db, "destinations");
    try {
        const document = await addDoc(collectionRef, {
            city: addCity,
            country: addCountry,
            imgUrl: addImgURL,
            category: addCategory,
            description: addDescription || ""
        });
        
        //sets the autogenerated id as an field in the document
        await updateDoc(doc(document.firestore, "destinations", document.id), { id: document.id });
    } catch (e) {
        console.error(e);
    }
  }

  async editDestination(destinationID: string, updateCity?: string, updateCountry?: string, updateImgURL?: string, updateCategories?: string[], updateDescription?: string) {
    const docRef = doc(db, "destinations", destinationID);
    try {
      await updateDoc(docRef, {
        city: updateCity,
        country: updateCountry,
        imgUrl: updateImgURL,
        category: updateCategories,
        description: updateDescription
      });
    }
    catch(e) {
      console.error(e);
    }
  }

  getAuthInstance() {
    return auth;
  }

  

};

export default firebaseControl;